---
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-yaml
    - id: destroyed-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.2
  hooks:
    - id: yamllint
      files: \.(yaml|yml)$
      types: [file, yaml]
      entry: yamllint --strict

- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.1.3
  hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$

# keep at bottom as these are slower
- repo: local
  hooks:
    - id: molecule
      name: molecule
      entry: molecule test --parallel
      language: system
      files: \.(yaml|yml)$
      pass_filenames: false
...
