---
# yamllint disable rule:line-length
- name: unattended_upgrades_verify
  hosts: instance
  tasks:
    - name: add test variables
      ansible.builtin.include_vars:
        file: "vars.yml"

    - name: APT::Periodic::Enable
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::Enable "{{ unattended_upgrades_enabled }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: APT::Periodic::Unattended-Upgrade
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::Unattended-Upgrade "{{ unattended_upgrades_upgrade }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: APT::Periodic::Update-Package-Lists
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::Update-Package-Lists "{{ unattended_upgrades_update_package_list }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: APT::Periodic::Download-Upgradeable-Packages
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::Download-Upgradeable-Packages "{{ unattended_upgrades_download_upgradeable }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: APT::Periodic::AutocleanInterval
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::AutocleanInterval "{{ unattended_upgrades_autoclean_interval }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: APT::Periodic::CleanInterval
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::CleanInterval "{{ unattended_upgrades_clean_interval }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: APT::Periodic::Verbose
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::Verbose "{{ unattended_upgrades_verbose }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: APT::Periodic::RandomSleep
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        line: APT::Periodic::RandomSleep "{{ unattended_upgrades_random_sleep }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Origins-Pattern
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Origins-Pattern {
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Package-Blacklist
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Package-Blacklist {
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::AutoFixInterruptedDpkg
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::AutoFixInterruptedDpkg "false";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::MinimalSteps
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::MinimalSteps "{{ unattended_upgrades_minimal_steps | lower }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::InstallOnShutdown
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::InstallOnShutdown "{{ unattended_upgrades_install_on_shutdown }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Mail
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Mail "{{ unattended_upgrades_mail }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::MailOnlyOnError
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::MailOnlyOnError "true";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Remove-Unused-Dependencies
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Remove-Unused-Dependencies "{{ unattended_upgrades_remove_unused_dependencies }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Remove-New-Unused-Dependencies
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Remove-New-Unused-Dependencies "{{ unattended_upgrades_remove_new_unused_dependencies }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Automatic-Reboot
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Automatic-Reboot "{{ unattended_upgrades_automatic_reboot }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Automatic-Reboot-Time
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Automatic-Reboot-Time "{{ unattended_upgrades_automatic_reboot_time }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::Update-Days
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::Update-Days {{ unattended_upgrades_update_days }};
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::IgnoreAppsRequireRestart
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::IgnoreAppsRequireRestart "true";
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::SyslogEnable
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Unattended-Upgrade::SyslogEnable "true";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Unattended-Upgrade::SyslogFacility
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: |
          Unattended-Upgrade::SyslogFacility "{{ unattended_upgrades_syslog_facility }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Dpkg::Options
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Dpkg::Options {
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed

    - name: Acquire::http::Dl-Limit
      ansible.builtin.lineinfile:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        line: Acquire::http::Dl-Limit "{{ unattended_upgrades_dl_limit }}";
      check_mode: true
      register: unattended_upgrades_verify
      failed_when: unattended_upgrades_verify.changed
...
